<section class="section about parallax" id="about" data-parallax data-img-width="1700" data-img-height="881" data-diff="100">
    <div class="container">
        <div class="about__text text col-md-7">
            <strong class="title about__title">ABOUT heart in&nbsp;diamond</strong>

            <p>Heart in&nbsp;Diamond is&nbsp;based in&nbsp;Castle Donington, Derby, Leicestershire, United Kingdom. Our US&nbsp;office is&nbsp;located in&nbsp;Commerce, Georgia, about an&nbsp;hour away from Atlanta.</p>
            <p>We’ve&nbsp;been in&nbsp;business turning human ashes and hair into memorial diamonds for more than 8 years. Even though they’re&nbsp;grown in&nbsp;a&nbsp;laboratory, our diamonds from ashes are 100% identical to&nbsp;naturally mined diamonds.</p>
            <p>We’re&nbsp;the only ashes to&nbsp;diamonds producer with our own diamond production facility. Every other company in&nbsp;the industry outsources their production to&nbsp;a&nbsp;third party. This means we&nbsp;guarantee you get your diamond months faster than you would with any other company, and you are guaranteed to&nbsp;pay the lowest prices available.</p>
            <blockquote>
                <p>Because they’re&nbsp;grown in&nbsp;laboratories, turning ashes into diamonds is&nbsp;a&nbsp;guaranteed <nobr>&laquo;conflict-free&raquo;</nobr> process. That means human beings were not enslaved, exploited, or&nbsp;harmed in&nbsp;any way to&nbsp;produce these diamonds (Unfortunately, that often happens with natural diamonds, where children can be&nbsp;used to&nbsp;mine them).</p>
            </blockquote>
            <p>And no&nbsp;damage is&nbsp;ever done to&nbsp;the environment (Mining natural diamonds often causes damage to&nbsp;the local environment so&nbsp;great that people can no&nbsp;longer liver there).</p>
            <p>Our consultants have all experienced tragic and difficult losses in&nbsp;their lives&nbsp;&mdash; just like you. Our kindness, compassion, and empathy shines through in&nbsp;every interaction. When possible, we’re&nbsp;happy to&nbsp;show you diamonds in&nbsp;person, and even deliver them ourselves straight to&nbsp;your door.even deliver them ourselves straight to&nbsp;your door.</p>
        </div>
        <a href="http://www.heart-in-diamond.com/index.php" class="button about__button" target="_blank">More about Heart in diamond</a>

        <div class="links about__links">
            <a href="http://www.heart-in-diamond.com/company/about.html" class="links__item" target="_blank">Our team</a>
            <span class="links__item links__item_separator">|</span>
            <a href="http://www.heart-in-diamond.com/company/certified-partners.html" class="links__item" target="_blank">Certified Partners</a>
            <span class="links__item links__item_separator">|</span>
            <a href="http://www.heart-in-diamond.com/diamonds/authenticity-guarantee.html" class="links__item" target="_blank">Guarantees</a>
            <span class="links__item links__item_separator">|</span>
            <a href="http://www.heart-in-diamond.com/orders/how-to-select-manufacturer.html" class="links__item" target="_blank">Select a Manufacturer</a>
        </div>
    </div>
</section>