<section class="section contacts parallax" id="contact" data-parallax data-img-width="1700" data-img-height="1133" data-diff="100">
    <div class="container">
        <strong class="contacts__title">Need More Time to&nbsp;Think It&nbsp;Over?</strong>

        <div class="contacts__intro">
            <p>Receive Your Free Information Kit, Free Consultation, and Special 5% Discount or&nbsp;Order Now by&nbsp;clicking the appropriate box below:</p>
        </div>

        <form action="" method="get" class="form form__contacts">
            <div class="form__actions">
                <label for="check-1" class="checkbox">
                    <input type="checkbox" name="check" id="check-1">
                    <span class="checkbox__text">I’m&nbsp;ready to&nbsp;order now, I&nbsp;know what I&nbsp;want. I’d&nbsp;like a&nbsp;consultant to&nbsp;call me</span>
                </label>
                <label for="check-2" class="checkbox">
                    <input type="checkbox" name="check" id="check-2">
                    <span class="checkbox__text">Yes, I&nbsp;want my&nbsp;FREE Information Kit (includes brochure, FAQ guide, purchase order form, and material collection kit)</span>
                </label>
                <label for="check-3" class="checkbox">
                    <input type="checkbox" name="check" id="check-3">
                    <span class="checkbox__text">Yes, I&nbsp;want a&nbsp;kind and caring rep to&nbsp;answer questions and give me&nbsp;my&nbsp;FREE consultation</span>
                </label>
                <label for="check-4" class="checkbox">
                    <input type="checkbox" name="check" id="check-4">
                    <span class="checkbox__text">Yes, I&nbsp;want to&nbsp;subscribe to&nbsp;your newsletter and get my&nbsp;FREE 5% discount</span>
                </label>
                <label for="check-5" class="checkbox">
                    <input type="checkbox" name="check" id="check-5">
                    <span class="checkbox__text">Yes, I want all 3 of these offers</span>
                </label>
            </div>

            <div class="form__inner">
                <div class="form__item">
                    <input type="text" class="field" placeholder="Name" name="name" required>
                </div>
                <div class="form__item">
                    <input type="tel" class="field" placeholder="TELEPHONE" name="phone">
                </div>
                <div class="form__item">
                    <input type="email" class="field" name="email" placeholder="EMAIL" required>
                </div>
                <div class="form__item">
                    <textarea class="field field_message" name="message" placeholder="YOUR MESSAGE" required></textarea>
                </div>
                <button class="button form__button" type="submit">Submit</button>

                <div class="contacts__phone-call-alternate">
                    <strong class="contacts__title">Or&nbsp;call&nbsp;us 1&nbsp;888&nbsp;1234567 </strong>
                </div>



                <div class="form__message"></div>
            </div>
        </form>
    </div>
</section>