<footer class="footer">
    <div class="container">
        <div class="footer__content">
            <div class="footer-contacts">
                <span class="footer-contacts__item footer-contacts__item_location">Atlanta, GA</span>
                <a href="tel:18881234567" class="footer-contacts__item footer-contacts__item_tel">1 888 1234567</a>
                <a href="#" class="footer-contacts__item footer-contacts__item_email" data-step=".contacts">Click to send a message</a>
            </div>
        </div>
        <div class="social footer__social">
            <a href="#" class="social__item social__item_blog">blog</a>
            <a href="#" class="social__item social__item_fb"></a>
            <a href="#" class="social__item social__item_tw"></a>
            <a href="#" class="social__item social__item_gp"></a>
            <a href="#" class="social__item social__item_pt"></a>
        </div>
        <a href="http://www.heart-in-diamond.com/index.php" class="footer__link">Check out our desktop version of the website!</a>

        <div class="footer__copyright">
            <span>
                Copyright &copy; Heart In&nbsp;Diamond 2016
            </span>
        </div>
    </div>
</footer>