<footer class="footer">
    <div class="container">
        <div class="footer__content">
            <div class="footer-contacts">
                <span class="footer-contacts__item footer-contacts__item_location">Atlanta, GA</span>
                <a href="tel:18881234567" class="footer-contacts__item footer-contacts__item_tel">1 888 1234567</a>
                <a href="#" class="footer-contacts__item footer-contacts__item_email" data-step=".contacts">Click to send a message</a>
            </div>
        </div>
        <div class="social footer__social">
            <a href="http://www.heart-in-diamond.com/news/" class="social__item social__item_blog" target="_blank">blog</a>
            <a href="http://www.facebook.com/heartindiamonds" class="social__item social__item_fb" target="_blank"></a>
            <a href="http://twitter.com/heartindiamond" class="social__item social__item_tw" target="_blank"></a>
            <a href="https://plus.google.com/116284473400462216151" class="social__item social__item_gp" target="_blank"></a>
            <a href="https://www.pinterest.com/heartindiamond/" class="social__item social__item_pt" target="_blank"></a>
        </div>
        <a href="http://www.heart-in-diamond.com/index.php" class="footer__link" target="_blank">Check out our desktop version of the website!</a>

        <div class="footer__copyright">
                        <span>
                            Copyright &copy; Heart In&nbsp;Diamond 2016
                        </span>
        </div>
    </div>
</footer>