<header class="header">
    <div class="header__content container">
        <a href="/" class="logo header__logo">
            <img src="build/images/header/logo.svg" alt="Heart In Diamond | Cremation Diamonds &amp; Hair to Diamonds">
        </a>
        <nav class="nav header__nav">
            <ul class="nav__list">
                <li class="nav__item">
                    <a href="#process" class="nav__link" data-scroll="#process">
                        <span class="nav__text">Process</span>
                    </a>
                </li>
                <li class="nav__item">
                    <a href="#step-1" class="nav__link" data-scroll="#step-1">
                        <span class="nav__text">Step 1</span>
                    </a>
                </li>
                <li class="nav__item">
                    <a href="#step-2" class="nav__link" data-scroll="#step-2">
                        <span class="nav__text">Step 2</span>
                    </a>
                </li>
                <li class="nav__item">
                    <a href="#step-3" class="nav__link" data-scroll="#step-3">
                        <span class="nav__text">Step 3</span>
                    </a>
                </li>
                <li class="nav__item">
                    <a href="#step-4" class="nav__link" data-scroll="#step-4">
                        <span class="nav__text">Step 4</span>
                    </a>
                </li>
                <li class="nav__item">
                    <a href="#step-5" class="nav__link" data-scroll="#step-5">
                        <span class="nav__text">Step 5</span>
                    </a>
                </li>
                <li class="nav__item">
                    <a href="#prices" class="nav__link" data-scroll="#prices">
                        <span class="nav__text">Prices</span>
                    </a>
                </li>
                <li class="nav__item">
                    <a href="#contact" class="nav__link" data-scroll="#contact">
                        <span class="nav__text">Contact</span>
                    </a>
                </li>
                <li class="nav__item">
                    <a href="#about" class="nav__link" data-scroll="#about">
                        <span class="nav__text">About</span>
                    </a>
                </li>
                <li class="nav__item">
                    <a href="http://www.heart-in-diamond.com/news/" class="nav__link" target="_blank" data-scroll="#">
                        <span class="nav__text">Blog</span>
                    </a>
                </li>
            </ul>
        </nav>
        <div class="header__button">
            <i class="header__button__line header__button__line_1"></i>
            <i class="header__button__line header__button__line_2"></i>
            <i class="header__button__line header__button__line_3"></i>
        </div>
    </div>
</header>