<section class="section info parallax" id="process" data-parallax data-img-width="1800" data-img-height="760" data-diff="100">
    <div class="section__content container">
        <strong class="section__title title">How Does Heart In&nbsp;Diamond Create Beautiful Diamonds from Your Loved One’s&nbsp;Hair or&nbsp;Ashes?</strong>

        <div class="row">
            <div class="col-md-7 info__text text">
                <div class="info__intro">
                    We&nbsp;follow a&nbsp;simple, <nobr>5-step</nobr> process to&nbsp;turn human ashes into diamonds that hold lasting memories of&nbsp;your loved one:
                </div>
                <ol>
                    <li>Select your memorial diamond</li>
                    <li>Select your setting (over 500 to&nbsp;choose from</li>
                    <li>Send your loved one’s&nbsp;(family member’s, relative’s, friend’s, or&nbsp;pet’s) hair or&nbsp;ashes</li>
                    <li>Our lab turns their ashes into diamonds</li>
                    <li>Receive your personal diamond</li>
                </ol>
                <p>Our kind and compassionate consultants guide you hand-in-hand through the process. They’ll stay in constant contact with you. You’ll feel special, loved, and valued.</p>
            </div>
        </div>
    </div>
</section>