<div class="intro">
    <div class="slideshow">
        <div class="slideshow__item slideshow__item_active" style="background-image: url(build/images/slideshow/slider1.jpg)"></div>
        <div class="slideshow__item" style="background-image: url(build/images/slideshow/slider2.jpg)"></div>
        <div class="slideshow__item" style="background-image: url(build/images/slideshow/slider3.jpg)"></div>
        <div class="slideshow__item" style="background-image: url(build/images/slideshow/slider4.jpg)"></div>
        <div class="slideshow__item" style="background-image: url(build/images/slideshow/slider5.jpg)"></div>
        <div class="slideshow__tint"></div>
    </div>
    <div class="intro__content container">
        <div class="intro__inner">
            <h2 class="intro__title">
                Take a&nbsp;Lasting Reminder of&nbsp;Your Loved One with You Everywhere You Go
            </h2>
            <div class="intro__text">
                Heart in&nbsp;Diamond creates stunningly beautiful diamonds from your deceased loved one’s&nbsp;hair or&nbsp;ashes so&nbsp;you can hold on&nbsp;to&nbsp;your special memories of&nbsp;them&nbsp;&mdash; forever.
            </div>

            <a href="#" class="intro__button" data-scroll-section="#process">learn more</a>
        </div>
    </div>
</div>