<div class="panel">

    <div class="panel__content">
        <div class="panel__content__inner">

            <ul class="panel-nav">
                <li class="panel-nav__item">
                    <a href="#process" class="panel-nav__link" data-scroll="#process">Process</a>
                </li>
                <li class="panel-nav__item">
                    <a href="#step-1" class="panel-nav__link" data-scroll="#step-1">Step 1</a>
                </li>
                <li class="panel-nav__item">
                    <a href="#step-2" class="panel-nav__link" data-scroll="#step-2">Step 2</a>
                </li>
                <li class="panel-nav__item">
                    <a href="#step-3" class="panel-nav__link" data-scroll="#step-3">Step 3</a>
                </li>
                <li class="panel-nav__item">
                    <a href="#step-4" class="panel-nav__link" data-scroll="#step-4">Step 4</a>
                </li>
                <li class="panel-nav__item">
                    <a href="#step-5" class="panel-nav__link" data-scroll="#step-5">Step 5</a>
                </li>
                <li class="panel-nav__item">
                    <a href="#prices" class="panel-nav__link" data-scroll="#prices">Prices</a>
                </li>
                <li class="panel-nav__item">
                    <a href="#contact" class="panel-nav__link" data-scroll="#contact">Contact</a>
                </li>
                <li class="panel-nav__item">
                    <a href="#about" class="panel-nav__link" data-scroll="#about">About</a>
                </li>
                <li class="panel-nav__item">
                    <a href="http://www.heart-in-diamond.com/news/" class="panel-nav__link" data-scroll="#" target="_blank">Blog</a>
                </li>
            </ul>

        </div>
    </div>

</div>