<section class="section prices" id="prices">
    <div class="container">
        <strong class="title prices__title">Prices</strong>

        <div class="prices__content">
            <div class="prices__intro">The Lowest Price For Your Precious Memorial Diamond. 100% Guaranteed.</div>
            <div class="prices__text text col-md-8">
                <p>We&nbsp;offer you the best price for your memorial diamond you’ll&nbsp;find anywhere. Unlike every other memorial diamond producer, we&nbsp;make your diamond in&nbsp;our own production facility. That’s&nbsp;what allows us&nbsp;to&nbsp;beat everyone else’s&nbsp;prices.</p>
                <p>Our &laquo;Price Match Guarantee&raquo; means we’ll&nbsp;beat a&nbsp;competitor if&nbsp;you do&nbsp;find a&nbsp;memorial diamond with a&nbsp;lower price.</p>
            </div>
        </div>

        <table class="table prices-table hidden-sm hidden-xs">

            <tr class="prices-table__head">
                <th class="prices-table__head-cell">OPTION CARAT</th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/orange.png" alt="">
                    </div>
                    <p>ORANGE - YELLOW</p>
                    <p>70 days</p>
                </th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/yellow.png" alt="">
                    </div>
                    <p>YELLOW - GREEN</p>
                    <p>70 days</p>
                </th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/red.png" alt="">
                    </div>
                    <p>DEEP - RED</p>
                    <p>70 days</p>
                </th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/blue.png" alt="">
                    </div>
                   <p>BLUE</p>
                    <p>120 days</p>
                </th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/white.png" alt="">
                    </div>
                    <p>WHITE</p>
                    <p>120 days</p>
                </th>
            </tr>

            <tr class="prices-table__row">
                <td class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_0"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">0.03 CARAT</div>
                </td>
                <td class="prices-table__cell">
                    <p>$1995</p>
                </td>
                <td class="prices-table__cell">
                    <p>$2295</p>
                </td>
                <td class="prices-table__cell">
                    <p>$2585</p>
                </td>
                <td class="prices-table__cell">
                    <p>$2585</p>
                </td>
                <td class="prices-table__cell">
                    <p>$2925</p>
                </td>
            </tr>
            <tr class="prices-table__row">
                <td class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_1"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">Budget<br>(0,10-0,19 ct)</div>
                </td>
                <td class="prices-table__cell">
                    <p>$1995</p>
                </td>
                <td class="prices-table__cell">
                    <p>$2295</p>
                </td>
                <td class="prices-table__cell">
                    <p>$2585</p>
                </td>
                <td class="prices-table__cell">
                    <p>$2585</p>
                </td>
                <td class="prices-table__cell">
                    <p>$2925</p>
                </td>
            </tr>
            <tr class="prices-table__row">
                <td class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_2"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac14;</span> CARAT</div>
                </td>
                <td class="prices-table__cell">
                    <p>$2625</p>
                </td>
                <td class="prices-table__cell">
                    <p>$3195</p>
                </td>
                <td class="prices-table__cell">
                    <p>$3215</p>
                </td>
                <td class="prices-table__cell">
                    <p>$3395</p>
                </td>
                <td class="prices-table__cell">
                    <p>$3415</p>
                </td>
            </tr>
            <tr class="prices-table__row">
                <td class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_3"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac12;</span> CARAT</div>
                </td>
                <td class="prices-table__cell">
                    <p>$5445</p>
                </td>
                <td class="prices-table__cell">
                    <p>$7145</p>
                </td>
                <td class="prices-table__cell">
                    <p>$7095</p>
                </td>
                <td class="prices-table__cell">
                    <p>$7785</p>
                </td>
                <td class="prices-table__cell">
                    <p>$7795</p>
                </td>
            </tr>
            <tr class="prices-table__row">
                <td class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_4"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac34;</span> CARAT</div>
                </td>
                <td class="prices-table__cell">
                    <p>$6845</p>
                </td>
                <td class="prices-table__cell">
                    <p>$7845</p>
                </td>
                <td class="prices-table__cell">
                    <p>$8345</p>
                </td>
                <td class="prices-table__cell">
                    <p>$12495</p>
                </td>
                <td class="prices-table__cell">
                    <p>$14995</p>
                </td>
            </tr>
            <tr class="prices-table__row">
                <td class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_5"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">1 CARAT</div>
                </td>
                <td class="prices-table__cell">
                    <p>$8945</p>
                </td>
                <td class="prices-table__cell">
                    <p>$9945</p>
                </td>
                <td class="prices-table__cell">
                    <p>$10165</p>
                </td>
                <td class="prices-table__cell">
                    <p>$19845</p>
                </td>
                <td class="prices-table__cell">
                    <p>-</p>
                </td>
            </tr>
            <tr class="prices-table__row">
                <td class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_7"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">1&frac14;</span> CARAT</div>
                </td>
                <td class="prices-table__cell">
                    <p>$10945</p>
                </td>
                <td class="prices-table__cell">
                    <p>$11945</p>
                </td>
                <td class="prices-table__cell">
                    <p>-</p>
                </td>
                <td class="prices-table__cell">
                    <p>-</p>
                </td>
                <td class="prices-table__cell">
                    <p>-</p>
                </td>
            </tr>
            <tr class="prices-table__row">
                <td class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_8"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">1&frac12;</span> CARAT</div>
                </td>
                <td class="prices-table__cell">
                    <p>$12945</p>
                </td>
                <td class="prices-table__cell">
                    <p>$14545</p>
                </td>
                <td class="prices-table__cell">
                    <p>-</p>
                </td>
                <td class="prices-table__cell">
                    <p>-</p>
                </td>
                <td class="prices-table__cell">
                    <p>-</p>
                </td>
            </tr>
            <tr class="prices-table__row">
                <td class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_9"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">2 CARAT</div>
                </td>
                <td class="prices-table__cell">
                    <p>$15545</p>
                </td>
                <td class="prices-table__cell">
                    <p>$16945</p>
                </td>
                <td class="prices-table__cell">
                    <p>-</p>
                </td>
                <td class="prices-table__cell">
                    <p>-</p>
                </td>
                <td class="prices-table__cell">
                    <p>-</p>
                </td>
            </tr>
        </table>

        <table class="table prices-table prices-table_small prices-table_small_1 hidden-lg hidden-md">

            <tr class="prices-table__head">
                <th class="prices-table__head-cell prices-table__head-cell_first">OPTION CARAT</th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/orange.png" alt="">
                    </div>
                    <p>ORANGE - YELLOW</p>
                    <p>70 days</p>
                </th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/yellow.png" alt="">
                    </div>
                    <p>YELLOW - GREEN</p>
                    <p>70 days</p>
                </th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/red.png" alt="">
                    </div>
                    <p>DEEP - RED</p>
                    <p>70 days</p>
                </th>
            </tr>

            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_0"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">0.03 CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$1995</p>
                </th>
                <th class="prices-table__cell">
                    <p>$2295</p>
                </th>
                <th class="prices-table__cell">
                    <p>$2585</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_1"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">Budget<br>(0,10-0,19 ct)</div>
                </th>
                <th class="prices-table__cell">
                    <p>$1995</p>
                </th>
                <th class="prices-table__cell">
                    <p>$2295</p>
                </th>
                <th class="prices-table__cell">
                    <p>$2585</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_2"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac14;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$2625</p>
                </th>
                <th class="prices-table__cell">
                    <p>$3195</p>
                </th>
                <th class="prices-table__cell">
                    <p>$3215</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_3"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac12;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$5445</p>
                </th>
                <th class="prices-table__cell">
                    <p>$7145</p>
                </th>
                <th class="prices-table__cell">
                    <p>$7095</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_4"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac34;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$6845</p>
                </th>
                <th class="prices-table__cell">
                    <p>$7845</p>
                </th>
                <th class="prices-table__cell">
                    <p>$8345</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_5"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">1 CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$8945</p>
                </th>
                <th class="prices-table__cell">
                    <p>$9945</p>
                </th>
                <th class="prices-table__cell">
                    <p>$10165</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_7"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">1&frac14;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$10945</p>
                </th>
                <th class="prices-table__cell">
                    <p>$11945</p>
                </th>
                <th class="prices-table__cell">
                    <p>-</p>
                </th>

            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_8"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">1&frac12;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$12945</p>
                </th>
                <th class="prices-table__cell">
                    <p>$14545</p>
                </th>
                <th class="prices-table__cell">
                    <p>-</p>
                </th>

            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_9"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">2 CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$15545</p>
                </th>
                <th class="prices-table__cell">
                    <p>$16945</p>
                </th>
                <th class="prices-table__cell">
                    <p>-</p>
                </th>

            </tr>
        </table>

        <table class="table prices-table prices-table_small prices-table_small_2 hidden-lg hidden-md">

            <tr class="prices-table__head">
                <th class="prices-table__head-cell prices-table__head-cell_first">OPTION CARAT</th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/blue.png" alt="">
                    </div>
                    <p>BLUE</p>
                    <p>120 days</p>
                </th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/white.png" alt="">
                    </div>
                    <p>WHITE</p>
                    <p>120 days</p>
                </th>
            </tr>

            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_0"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">0.03 CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$2585</p>
                </th>
                <th class="prices-table__cell">
                    <p>$2925</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_1"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">Budget<br>(0,10-0,19 ct)</div>
                </th>
                <th class="prices-table__cell">
                    <p>$2585</p>
                </th>
                <th class="prices-table__cell">
                    <p>$2925</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_2"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac14;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$3395</p>
                </th>
                <th class="prices-table__cell">
                    <p>$3415</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_3"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac12;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$7785</p>
                </th>
                <th class="prices-table__cell">
                    <p>$7795</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_4"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac34;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$12495</p>
                </th>
                <th class="prices-table__cell">
                    <p>$14995</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_5"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">1 CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$19845</p>
                </th>
                <th class="prices-table__cell">
                    <p>-</p>
                </th>
            </tr>
        </table>


        <table class="table prices-table prices-table_small prices-table_small_3 hidden-lg hidden-md">

            <tr class="prices-table__head">
                <th class="prices-table__head-cell prices-table__head-cell_first">OPTION CARAT</th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/orange.png" alt="">
                    </div>
                    <p>ORANGE - YELLOW</p>
                    <p>70 days</p>
                </th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/yellow.png" alt="">
                    </div>
                    <p>YELLOW - GREEN</p>
                    <p>70 days</p>
                </th>
            </tr>

            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_0"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">0.03 CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$1995</p>
                </th>
                <th class="prices-table__cell">
                    <p>$2295</p>
                </th>

            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_1"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">Budget<br>(0,10-0,19 ct)</div>
                </th>
                <th class="prices-table__cell">
                    <p>$1995</p>
                </th>
                <th class="prices-table__cell">
                    <p>$2295</p>
                </th>

            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_2"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac14;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$2625</p>
                </th>
                <th class="prices-table__cell">
                    <p>$3195</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_3"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac12;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$5445</p>
                </th>
                <th class="prices-table__cell">
                    <p>$7145</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_4"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac34;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$6845</p>
                </th>
                <th class="prices-table__cell">
                    <p>$7845</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_5"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">1 CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$8945</p>
                </th>
                <th class="prices-table__cell">
                    <p>$9945</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_7"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">1&frac14;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$10945</p>
                </th>
                <th class="prices-table__cell">
                    <p>$11945</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_8"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">1&frac12;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$12945</p>
                </th>
                <th class="prices-table__cell">
                    <p>$14545</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_9"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">2 CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$15545</p>
                </th>
                <th class="prices-table__cell">
                    <p>$16945</p>
                </th>
            </tr>
        </table>
        <table class="table prices-table prices-table_small prices-table_small_4 hidden-lg hidden-md">

            <tr class="prices-table__head">
                <th class="prices-table__head-cell prices-table__head-cell_first">OPTION CARAT</th>
                <th class="prices-table__head-cell">
                    <div class="prices-table__diamonds">
                        <img src="build/images/prices/red.png" alt="">
                    </div>
                    <p>DEEP - RED</p>
                    <p>70 days</p>
                </th>
            </tr>

            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_0"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">0.03 CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$2585</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_1"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">Budget<br>(0,10-0,19 ct)</div>
                </th>
                <th class="prices-table__cell">
                    <p>$2585</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_2"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac14;</span> CARAT</div>
                </th>

                <th class="prices-table__cell">
                    <p>$3215</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_3"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac12;</span> CARAT</div>
                </th>
                <th class="prices-table__cell">
                    <p>$7095</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_4"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2"><span class="prices-table__fraction fraction">&frac34;</span> CARAT</div>
                </th>

                <th class="prices-table__cell">
                    <p>$8345</p>
                </th>
            </tr>
            <tr class="prices-table__row">
                <th class="prices-table__cell prices-table__cell_first">
                    <div class="prices-table__cell-part prices-table__cell-part_1">
                        <span class="carat carat_5"></span>
                    </div>
                    <div class="prices-table__cell-part prices-table__cell-part_2">1 CARAT</div>
                </th>

                <th class="prices-table__cell">
                    <p>$10165</p>
                </th>
            </tr>
        </table>
    </div>
</section>