<!-- rings -->

<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>

<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>

<!-- earrings -->

<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>

<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>

<!-- pendants -->

<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>

<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>