<!-- rings -->

<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121570_1_y_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/67547_1_w_wh.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121681_1_y_re.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121710_1_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/140401L_1_gr.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/4929a_1_y_re.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/150401_1_yw_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/121602_1_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/15720043_1w_re.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="rings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/12598_1_or.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>

<!-- earrings -->

<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/2983_1_y_wh.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/22137_1_w_wh.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/85033_1_or.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/62867_1_gr.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>

<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/66234_1_y_wh.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/84989_1_y_or.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/66418_1_bl.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/61086_1_y_wh.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/20318_1_w_gr.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="earrings product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/22137_1_or.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>

<!-- pendants -->

<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/81487_1_gr.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/81537_1_y_or.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/83534_1_y_or.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/83761_1_w_wh.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>

<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/20934_1_w_wh.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/82206_1_gr.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/83127_1_w_re.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/81990_1_w_re.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/66744_1_re.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>
<div class="pendants product" data-category="post-transition">
    <div class="element-item-inner product__inner">
        <div class="product__picture" style="background-image: url(http://www.heart-in-diamond.com/img/jewelry/20934_1_w_re.jpg);"></div>
        <div class="inner-content product__content">
            <div class="product__content-inner same-resize">
                <h4 class="product__title">Halo 18K Yellow</h4>
                <div class="product__price">$1937</div>
                <a href="#" class="product__button">View More</a>
            </div>
        </div>
    </div>
</div>