<section class="section step-five parallax" data-parallax data-img-width="1700" data-img-height="616" data-diff="100" id="step-5">
    <div class="section__content container">
        <strong class="title">Step 5: Receive Your Personal Diamond And Forever Enjoy Lasting Memories of&nbsp;Your Loved One</strong>

        <div class="step-five__text text col-md-7">
            <p>When possible, our consultants deliver you your treasured diamond in&nbsp;person. If&nbsp;not, you’ll&nbsp;receive it&nbsp;from an&nbsp;authorized courier.</p>
            <p>During the shipping process, your diamond is&nbsp;fully insured, so&nbsp;you don’t&nbsp;have to&nbsp;worry about damage or&nbsp;loss.</p>
            <p>With your stunningly beautiful diamond, you now get to&nbsp;carry the most special feeling in&nbsp;the world with you all the time. Friends, family, neighbors, and coworkers will comment on&nbsp;how much they love your gorgeous memorial diamond.</p>
            <p>You’ll&nbsp;have a&nbsp;tangible reminder to&nbsp;help you cherish the most important loved one in&nbsp;your life. If&nbsp;you’re&nbsp;going through a&nbsp;difficult time or&nbsp;personal tragedy, it’s</p>
        </div>
    </div>
</section>