<section class="section step-four" id="step-4">
    <div class="section__content container">
        <strong class="title step-four__title">Step 4: Creation of&nbsp;Your Diamonds Made from Ashes&nbsp;&mdash; Get Yours Months Faster Than Anywhere Else&nbsp;&mdash; Guaranteed</strong>
        <div class="step-four__text text">
            <p>In&nbsp;this step of&nbsp;the process, you get to&nbsp;relax. You don’t&nbsp;have to&nbsp;do&nbsp;anything while our specialists create your diamond in&nbsp;our production facility.</p>
            <p>Sit back and relax&nbsp;&mdash; our consultants stay in&nbsp;constant contact with you during every step. You’ll&nbsp;know exactly how your diamond is&nbsp;doing during its entire journey. You can also visit this special tracking link to&nbsp;get online updates of&nbsp;your diamond’s&nbsp;progress.</p>
            <p>Depending on&nbsp;the color you choose, expect a&nbsp;wait of&nbsp;70&nbsp;&mdash; 120 days. In&nbsp;the memorial diamond industry, this is&nbsp;the guaranteed fastest production time available.</p>
            <p>Other companies take 5 months longer to&nbsp;produce a&nbsp;diamond of&nbsp;the exact same quality and color. We’re&nbsp;able to&nbsp;reduce production time dramatically because we’re&nbsp;the only memorial diamond company that owns our own production facility that turns cremated ashes into diamonds. Every other company outsources this process to&nbsp;a&nbsp;third party.</p>
        </div>
    </div>
</section>