<section class="section step-two" id="step-2">
    <div class="container">
        <strong class="title">Step 2: Select Your Setting from Over 500 Elegant Styles</strong>

        <div class="step-two__text text">
            <p>There’s&nbsp;a&nbsp;perfect setting in&nbsp;our selection that fits your most cherished memories of&nbsp;the loved one you adore. Your friends and family members will absolutely love your gorgeous memorial too.</p>
            <p>When you order your setting and diamond, you receive a&nbsp;special identification number. This number tracks the status of&nbsp;your diamond throughout the creation process.</p>
        </div>
    </div>
    <div class="products">
        <div class="row">
            <div class="filter col-md-8 col-xs-10">
                <a href="#" class="filter__item active" data-filter=".rings">Browse RINGS</a>
                <a href="#" class="filter__item" data-filter=".earrings">Browse EARRINGS</a>
                <a href="#" class="filter__item" data-filter=".pendants">Browse PENDANTS</a>
            </div>
        </div>
        <div class="isotope">
            <div class="products__list">
                <? include('includes/rings.inc'); ?>
            </div>
        </div>
    </div>
</section>