<section class="steps">
    <div class="container">
        <div class="step step_odd">
            <div class="step__content">
                <strong class="step__title">Turning Your Loved One’s&nbsp;Ashes into Diamonds: Step 1</strong>
                <div class="step__picture step__picture_mobile">
                    <img src="build/images/steps/1.jpg" alt="Step 1">
                </div>
                <div class="step__text text">
                    <p>When you order your diamond, it&nbsp;receives a&nbsp;special identification number. That unique ID&nbsp;number gets assigned to&nbsp;your case container.</p>
                    <p>It’s&nbsp;used to&nbsp;trace the progress of&nbsp;your diamond as&nbsp;it&nbsp;grows, guaranteeing it&nbsp;stays safe and secure during the entire creation process.</p>
                    <p>And you’ll&nbsp;be&nbsp;sure you in&nbsp;fact get your diamond when it&nbsp;gets delivered later on.</p>
                </div>
            </div>
            <div class="step__picture">
                <img src="build/images/steps/1.jpg" alt="Step 1">
            </div>
        </div>
        <div class="step step_even">
            <div class="step__picture">
                <img src="build/images/steps/2.jpg" alt="Step 2">
            </div>
            <div class="step__content">
                <strong class="step__title">Turning Your Loved One’s&nbsp;Ashes into Diamonds: Step 2</strong>
                <div class="step__picture step__picture_mobile">
                    <img src="build/images/steps/2.jpg" alt="Step 2">
                </div>
                <div class="step__text text">
                    <p>When our specialists receive your sample, they perform an&nbsp;analysis. After completing the analysis, the carbon in&nbsp;your sample is&nbsp;extracted and added to&nbsp;the diamond growing foundation.</p>
                    <p>From this, a&nbsp;100% unique diamond grows. Your diamond’s&nbsp;unique ID&nbsp;gets inscribed by&nbsp;laser directly into your diamond’s&nbsp;girdle.</p>
                </div>
            </div>
        </div>
        <div class="step step_odd">
            <div class="step__content">
                <strong class="step__title">Turning Your Loved One’s&nbsp;Ashes into Diamonds: Step 3</strong>
                <div class="step__picture step__picture_mobile">
                    <img src="build/images/steps/3.jpg" alt="Step 2">
                </div>
                <div class="step__text text">
                    <p>The mixture created in&nbsp;step 2 is&nbsp;placed in&nbsp;a&nbsp;High Pressure High Temperature (HPHT) machine. This machine mimics the process diamonds go&nbsp;through when they grow naturally in&nbsp;the Earth’s&nbsp;crust.</p>
                    <p>Your diamond gets placed under an&nbsp;intense pressure of&nbsp;60,000 atmospheres and an&nbsp;extreme temperature of&nbsp;3,632&deg;F!</p>
                </div>
            </div>
            <div class="step__picture">
                <img src="build/images/steps/3.jpg" alt="Step 3">
            </div>
        </div>
        <div class="step step_even">
            <div class="step__picture">
                <img src="build/images/steps/4.jpg" alt="Step 4">
            </div>
            <div class="step__content">
                <strong class="step__title">Turning Your Loved One’s&nbsp;Ashes into Diamonds: Step 4</strong>
                <div class="step__picture step__picture_mobile">
                    <img src="build/images/steps/4.jpg" alt="Step 2">
                </div>
                <div class="step__text text">
                    <p>When your diamond finishes growing, our specialists polish and cut it&nbsp;to&nbsp;meet the same industry grading standards that govern natural diamonds. Your diamond is&nbsp;100% real and receives a&nbsp;grade according to&nbsp;the 4 Cs: color, clarity, cut, and carat.</p>
                </div>
            </div>
        </div>
    </div>
</section>