<section class="section step-one" id="step-1">
    <div class="section__content container">
        <strong class="title">Step 1: Select Your <nobr>&laquo;Conflict-Free&raquo;</nobr> Memorial Diamond without Any Guilt or&nbsp;Worry</strong>

        <div class="step-one__text text">
            <p>First, you’ll&nbsp;<b>chooshe your diamond</b> with the help of&nbsp;our sensitive, thoughtful consultants. All cremation diamonds are laboratory grown over a&nbsp;period of&nbsp;just months in&nbsp;our own production facility.</p>
            <p>Our <nobr>laboratory-made</nobr> diamonds, unlike natural diamonds, <b>do&nbsp;not cause any harm</b> to&nbsp;Earth’s&nbsp;environment (Digging deep into Earth for diamonds destroys the environment so&nbsp;much local populations sometimes have to&nbsp;relocate).</p>
            <p>And laboratory diamonds are <b>guaranteed 100%</b> <nobr>&laquo;conflict-free&raquo;</nobr> because they’re&nbsp;<b>made by&nbsp;experienced professionals</b>. Natural diamonds are often harvested by&nbsp;slaves&nbsp;&mdash; even children&nbsp;&mdash; and the profits from them can be&nbsp;used to&nbsp;fund wars and terrorism.</p>
            <p>Regardless of&nbsp;which diamond you choose to&nbsp;<b>commemorate your loved one</b>, you buy it&nbsp;with a&nbsp;totally clear conscience. If&nbsp;possible, our consultants will even come to&nbsp;visit you in&nbsp;person.</p>
        </div>

        <div class="colors">
            <div class="colors__title title-underline">Colors</div>
            <div class="colors__list">
                <div class="colors__item">
                    <div class="colors__item-picture">
                        <img class="img-responsive" src="build/images/colors/blue.png" alt="Blue">
                    </div>
                    <div class="label label_blue">Blue</div>
                </div>
                <div class="colors__item colors__item_white">
                    <div class="colors__item-picture colors__item-picture_white">
                        <img class="img-responsive" src="build/images/colors/white.png" alt="White">
                    </div>
                    <div class="label label_white">White</div>
                </div>
                <div class="colors__item">
                    <div class="colors__item-picture">
                        <img class="img-responsive" src="build/images/colors/orange.png" alt="Orange-Yellow">
                    </div>
                    <div class="label label_orange">Orange - Yellow</div>
                </div>
                <div class="colors__item colors__item_green">
                    <div class="colors__item-picture colors__item-picture_green">
                        <img class="img-responsive" src="build/images/colors/green.png" alt="Yellow-Green">
                    </div>
                    <div class="label label_green">Yellow - Green</div>
                </div>
                <div class="colors__item">
                    <div class="colors__item-picture">
                        <img class="img-responsive" src="build/images/colors/red.png" alt="Deep Red">
                    </div>
                    <div class="label label_red">Deep Red</div>
                </div>
            </div>
        </div>

        <div class="cuts">
            <div class="cuts__title title-underline">Cuts</div>
            <div class="cuts__list col-md-8">
                <div class="cuts__item">
                    <div class="cuts__item-picture">
                        <img src="build/images/cuts/brilliant.png" alt="Brilliant">
                    </div>
                    <div class="label">Brilliant</div>
                </div>
                <div class="cuts__item col-md-4">
                    <div class="cuts__item-picture">
                        <img src="build/images/cuts/princess.png" alt="Princess">
                    </div>
                    <div class="label">Princess</div>
                </div>
                <div class="cuts__item col-md-4">
                    <div class="cuts__item-picture">
                        <img src="build/images/cuts/radiant.png" alt="Radiant">
                    </div>
                    <div class="label">Radiant</div>
                </div>
            </div>
        </div>

        <div class="step-one__weight">
            <div class="title-underline">Weight options</div>

            <table class="table table-weight hidden-sm hidden-xs hidden-md">

                <tr class="table-weight__head">
                    <th class="table-weight__head-cell table-weight__head-cell_first">NAME</th>
                    <th class="table-weight__head-cell">MINI - MID</th>
                    <th class="table-weight__head-cell">BUDGET</th>
                    <th class="table-weight__head-cell"><span class="table-weight__fraction fraction">&frac14;</span> CARAT</th>
                    <th class="table-weight__head-cell"><span class="table-weight__fraction fraction">&frac12;</span> CARAT</th>
                    <th class="table-weight__head-cell"><span class="table-weight__fraction fraction">&frac34;</span> CARAT</th>
                    <th class="table-weight__head-cell">1 CARAT</th>
                    <th class="table-weight__head-cell">1 <span class="table-weight__fraction fraction">&frac14;</span> CARAT</th>
                    <th class="table-weight__head-cell">1 <span class="table-weight__fraction fraction">&frac12;</span> CARAT</th>
                    <th class="table-weight__head-cell">2 CARATS</th>
                </tr>

                <tr class="table-weight__row">
                    <td class="table-weight__cell table-weight__cell_first"><p>CARAT</p></td>
                    <td class="table-weight__cell">
                        <span class="carat carat_1"></span>
                        <p>0.015 - 0.04</p>
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_2"></span>
                        <p>0.10 - 0.19</p>
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_3"></span>
                        <p>0.20 - 0.34</p>
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_4"></span>
                        <p>0.45 - 0.64</p>
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_5"></span>
                        <p>0.65 - 0.89</p>
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_6"></span>
                        <p>0.90 - 1.19</p>
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_7"></span>
                        <p>1.20 - 1.39</p>
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_8"></span>
                        <p>1.40 - 1.59</p>
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_9"></span>
                        <p>1.90 - 2.09</p>
                    </td>
                </tr>
            </table>

            <table class="table table-weight table-weight_mobile_1 hidden-lg">

                <tr class="table-weight__head">
                    <th class="table-weight__head-cell table-weight__head-cell_first">NAME</th>
                    <th class="table-weight__head-cell">MINI - MID</th>
                    <th class="table-weight__head-cell">BUDGET</th>
                    <th class="table-weight__head-cell"><span class="table-weight__fraction fraction">&frac14;</span> CARAT</th>
                    <th class="table-weight__head-cell"><span class="table-weight__fraction fraction">&frac12;</span> CARAT</th>
                    <th class="table-weight__head-cell"><span class="table-weight__fraction fraction">&frac34;</span> CARAT</th>
                </tr>

                <tr class="table-weight__row">
                    <th class="table-weight__cell table-weight__cell_first"><p>CARAT</p></th>
                    <th class="table-weight__cell">
                        <span class="carat carat_1"></span>
                        <p>0.015 - 0.04</p>
                    </th>
                    <th class="table-weight__cell">
                        <span class="carat carat_2"></span>
                        <p>0.10 - 0.19</p>
                    </th>
                    <th class="table-weight__cell">
                        <span class="carat carat_3"></span>
                        <p>0.45 - 0.64</p>
                    </th>
                    <th class="table-weight__cell">
                        <span class="carat carat_4"></span>
                        <p>0.65 - 0.69</p>
                    </th>
                    <th class="table-weight__cell">
                        <span class="carat carat_5"></span>
                        <p>0.65 - 0.89</p>
                    </th>
                </tr>
            </table>
            <table class="table table-weight table-weight_mobile_2 hidden-lg">

                <tr class="table-weight__head">
                    <th class="table-weight__head-cell table-weight__head-cell_first">NAME</th>
                    <th class="table-weight__head-cell">1 CARAT</th>
                    <th class="table-weight__head-cell">1 <span class="table-weight__fraction fraction">&frac14;</span> CARAT</th>
                    <th class="table-weight__head-cell">1 <span class="table-weight__fraction fraction">&frac12;</span> CARAT</th>
                    <th class="table-weight__head-cell">2 CARATS</th>
                </tr>

                <tr class="table-weight__row">
                    <th class="table-weight__cell table-weight__cell_first"><p>CARAT</p></th>
                    <th class="table-weight__cell">
                        <span class="carat carat_5"></span>
                        <p>0.90 - 1.19</p>
                    </th>
                    <th class="table-weight__cell">
                        <span class="carat carat_6"></span>
                        <p>1.20 - 1.39</p>
                    </th>
                    <th class="table-weight__cell">
                        <span class="carat carat_7"></span>
                        <p>1.40 - 1.59</p>
                    </th>
                    <th class="table-weight__cell">
                        <span class="carat carat_8"></span>
                        <p>1.90 - 2.09</p>
                    </th>
                </tr>
            </table>

            <table class="table-weight table-weight_mobile--xs hidden-sm hidden-md hidden-lg">
                <tr class="table-weight__head">
                    <th class="table-weight__head-cell table-weight__head-cell_mobile">NAME</th>
                    <th class="table-weight__head-cell table-weight__head-cell_mobile">CARAT</th>
                </tr>
                <tr class="table-weight__row">
                    <td class="table-weight__cell">
                        MINI - MID
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_1"></span>

                        <p>0.015 - 0.04</p>
                    </td>
                </tr>
                <tr class="table-weight__row">
                    <td class="table-weight__cell">
                        BUDGET
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_2"></span>

                        <p>0.10 - 0.19</p>
                    </td>
                </tr>
                <tr class="table-weight__row">
                    <td class="table-weight__cell">
                        <span class="table-weight__fraction fraction">&frac14;</span> CARAT
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_3"></span>

                        <p>0.45 - 0.64</p>
                    </td>
                </tr>
                <tr class="table-weight__row">
                    <td class="table-weight__cell">
                        <span class="table-weight__fraction fraction">&frac12;</span> CARAT
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_4"></span>

                        <p>0.65 - 0.69</p>
                    </td>
                </tr>
                <tr class="table-weight__row">
                    <td class="table-weight__cell">
                        <span class="table-weight__fraction fraction">&frac34;</span> CARAT
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_5"></span>

                        <p>0.65 - 0.89</p>
                    </td>
                </tr>
                <tr class="table-weight__row">
                    <td class="table-weight__cell">
                        1 CARAT
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_6"></span>

                        <p>0.90 - 1.19</p>
                    </td>
                </tr>
                <tr class="table-weight__row">
                    <td class="table-weight__cell">
                        1 <span class="table-weight__fraction fraction">&frac14;</span> CARAT
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_7"></span>

                        <p>1.20 - 1.39</p>
                    </td>
                </tr>
                <tr class="table-weight__row">
                    <td class="table-weight__cell">
                        1 <span class="table-weight__fraction fraction">&frac12;</span> CARAT
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_8"></span>

                        <p>1.40 - 1.59</p>
                    </td>
                </tr>
                <tr class="table-weight__row">
                    <td class="table-weight__cell">
                        2 CARATS
                    </td>
                    <td class="table-weight__cell">
                        <span class="carat carat_9"></span>

                        <p>1.90 - 2.09</p>
                    </td>
                </tr>
            </table>

        </div>

        <div class="videos">
            <div class="title-underline">EXPLANATION VIDEOS</div>
            <div class="videos__zone">
                <iframe class="videos__zone-frame" src="https://www.youtube.com/embed/s7z8P6iMf-E" frameborder="0" allowfullscreen></iframe>
            </div>

            <div class="videos__list hidden-sm hidden-xs">
                <div class="videos__item" data-action data-video="https://www.youtube.com/embed/s7z8P6iMf-E">
                    <div class="videos__item-picture videos__list--hidden-some-md" style="background-image: url(build/images/videos/blue.jpg)">
                        <div class="videos__item-play"></div>
                    </div>
                    <div class="videos__item-label">Blue Round Cut</div>
                </div>
                <div class="videos__item" data-action data-video="https://www.youtube.com/embed/BF0kI3RQOdw">
                    <div class="videos__item-picture" style="background-image: url(build/images/videos/orange.jpg)">
                        <div class="videos__item-play"></div>
                    </div>
                    <div class="videos__item-label">Orange Round Cut</div>
                </div>
                <div class="videos__item" data-action data-video="https://www.youtube.com/embed/QiNefjm84MM">
                    <div class="videos__item-picture" style="background-image: url(build/images/videos/red.jpg)">
                        <div class="videos__item-play"></div>
                    </div>
                    <div class="videos__item-label">Red Round Cut</div>
                </div>
                <div class="videos__item" data-action data-video="https://www.youtube.com/embed/3_qyGplcyXw">
                    <div class="videos__item-picture" style="background-image: url(build/images/videos/green.jpg)">
                        <div class="videos__item-play"></div>
                    </div>
                    <div class="videos__item-label">Green Round Cut</div>
                </div>
                <div class="videos__item" data-action data-video="https://www.youtube.com/embed/BF0kI3RQOdw">
                    <div class="videos__item-picture" style="background-image: url(build/images/videos/orange-p.jpg)">
                        <div class="videos__item-play"></div>
                    </div>
                    <div class="videos__item-label">Orange Princess Cut</div>
                </div>
                <div class="videos__item" data-action data-video="https://www.youtube.com/embed/rMEBJeaRmXw">
                    <div class="videos__item-picture" style="background-image: url(build/images/videos/red-p.jpg)">
                        <div class="videos__item-play"></div>
                    </div>
                    <div class="videos__item-label">Red Princess Cut</div>
                </div>
                <div class="videos__item" data-action data-video="https://www.youtube.com/embed/3_qyGplcyXw">
                    <div class="videos__item-picture" style="background-image: url(build/images/videos/green-p.jpg)">
                        <div class="videos__item-play"></div>
                    </div>
                    <div class="videos__item-label">Green Princess Cut</div>
                </div>
                <div class="videos__item" data-action data-video="https://www.youtube.com/embed/w7uWxetWspQ">
                    <div class="videos__item-picture" style="background-image: url(build/images/videos/white.jpg)">
                        <div class="videos__item-play"></div>
                    </div>
                    <div class="videos__item-label">White Round Cut</div>
                </div>
            </div>

            <div class="videos-labels hidden-lg hidden-md">
                <div class="videos-labels__item" data-action data-video="https://www.youtube.com/embed/s7z8P6iMf-E">
                    <div class="videos-labels__inner">
                        <div class="videos-labels__label">Blue Round Cut</div>
                    </div>
                </div>
                <div class="videos-labels__item" data-action data-video="https://www.youtube.com/embed/BF0kI3RQOdw">
                    <div class="videos-labels__inner">
                        <div class="videos-labels__label">Orange Round Cut</div>
                    </div>
                </div>
                <div class="videos-labels__item" data-action data-video="https://www.youtube.com/embed/QiNefjm84MM">
                    <div class="videos-labels__inner">
                        <div class="videos-labels__label">Red Round Cut</div>
                    </div>
                </div>
                <div class="videos-labels__item" data-action data-video="https://www.youtube.com/embed/3_qyGplcyXw">
                    <div class="videos-labels__inner">
                        <div class="videos-labels__label">Green Round Cut</div>
                    </div>
                </div>
                <div class="videos-labels__item" data-action data-video="https://www.youtube.com/embed/BF0kI3RQOdw">
                    <div class="videos-labels__inner">
                        <div class="videos-labels__label">Orange Princess Cut</div>
                    </div>
                </div>
                <div class="videos-labels__item" data-action data-video="https://www.youtube.com/embed/rMEBJeaRmXw">
                    <div class="videos-labels__inner">
                        <div class="videos-labels__label">Red Princess Cut</div>
                    </div>
                </div>
                <div class="videos-labels__item" data-action data-video="https://www.youtube.com/embed/3_qyGplcyXw">
                    <div class="videos-labels__inner">
                        <div class="videos-labels__label">Green Princess Cut</div>
                    </div>
                </div>
                <div class="videos-labels__item" data-action data-video="https://www.youtube.com/embed/w7uWxetWspQ">
                    <div class="videos-labels__inner">
                        <div class="videos-labels__label">White Round Cut</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
