<section class="section step-three" id="step-3">
    <div class="section__content container">
        <strong class="title">Step 3: Send Your Loved One’s&nbsp;Hair or&nbsp;Cremation Ashes to&nbsp;Turn into Diamonds</strong>

        <div class="step-three__content">
            <!--<div class="step-three__video">-->
                <!--<iframe src="https://www.youtube.com/embed/-ZNyGrkFo4w?autoplay=1" frameborder="0" allowfullscreen></iframe>-->
				<!--<div class="step-three__video-cap" style="background-image: url(build/images/cap.jpg)" data-video-cap data-video="https://www.youtube.com/embed/-ZNyGrkFo4w?autoplay=1"></div>-->
            <!--</div>-->

            <div class="step-three__video" data-video-cap data-video="https://www.youtube.com/embed/-ZNyGrkFo4w?autoplay=1">
                <iframe src="" frameborder="0" allowfullscreen></iframe>
                <div class="step-three__video-cap" style="background-image: url(build/images/cap.jpg)"></div>
            </div>

            <div class="step-three__text text">
                <p>Now that you’ve&nbsp;chosen your diamond and setting, it’s&nbsp;time to&nbsp;provide your loved one’s&nbsp;remains. Some clients combine hair from living family members. Others want only their loved one’s&nbsp;cremation ashes turned into diamonds. It’s&nbsp;your choice.</p>
                <p>Our laboratory specialists need cup of&nbsp;cremated ashes or&nbsp;&#189; cup of&nbsp;hair for each diamond you’d&nbsp;like.</p>
                <p>You can combine both samples.</p>
                <p>If&nbsp;you don’t&nbsp;have the precise amounts of&nbsp;hair or&nbsp;ashes available, don’t&nbsp;worry. Your memorial diamond can easily be&nbsp;created with additional generic carbon.</p>
            </div>

            <div class="step-three__video step-three__video_mobile" data-video-cap data-video="https://www.youtube.com/embed/-ZNyGrkFo4w?autoplay=1">
                <iframe src="" frameborder="0" allowfullscreen></iframe>
                <div class="step-three__video-cap" style="background-image: url(build/images/cap.jpg)"></div>
            </div>
        </div>
    </div>
</section>