<head>
    <title>Heart In Diamond | Hair or Ashes to Diamonds Specialists</title>
    <!-- Meta -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1" />
    <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="google" content="notranslate" />
    <!-- Favicon -->
    <link href="build/images/common/favicon.ico" rel="shortcut icon">
    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,800italic,700' rel='stylesheet'/>
    <!-- CSS -->
    <link href="build/css/style.css" rel="stylesheet" />
</head>